# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hWxTdns1KMJY4xR19tHWA0Owm24n3Zkp
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

data = {
    'Area': [1200, 1500, 1800, 2400, 3000,
             3500, 4000, 4500, 5000, 5500],

    'Bedrooms': [2, 3, 3, 4, 5,
                  5, 6, 6, 7, 7],

    'Age': [10, 5, 8, 2, 1,
            3, 2, 4, 1, 2],

    'Distance': [5, 3, 4, 2, 1,
                 2, 1, 3, 2, 1],

    'Price': [250, 320, 340, 450, 600,
              650, 700, 720, 800, 850]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display Dataset
print("\nDATASET\n")
print(df)

# Independent variables
X = df[['Area', 'Bedrooms', 'Age', 'Distance']]

# Dependent variable
y = df['Price']

model = LinearRegression()

model.fit(X, y)

y_pred = model.predict(X)

print("\nMODEL PARAMETERS\n")

print("Intercept:")
print(model.intercept_)

print("\nCoefficients:")
for feature, coef in zip(X.columns, model.coef_):
    print(feature, ":", coef)

print("\nREGRESSION EQUATION\n")

print("Price = ")

for feature, coef in zip(X.columns, model.coef_):
    print(f"({coef:.4f} * {feature}) + ")

print(model.intercept_)

mse = mean_squared_error(y, y_pred)

r2 = r2_score(y, y_pred)

print("\nEVALUATION METRICS\n")

print("Mean Squared Error (MSE):", round(mse, 4))

print("R² Score:", round(r2, 4))

mse = mean_squared_error(y, y_pred)

r2 = r2_score(y, y_pred)

print("\nEVALUATION METRICS\n")

print("Mean Squared Error (MSE):", round(mse, 4))

print("R² Score:", round(r2, 4))

new_house = pd.DataFrame({
    'Area': [2800],
    'Bedrooms': [4],
    'Age': [2],
    'Distance': [2]
})
predicted_price = model.predict(new_house)

print("\nNEW HOUSE PREDICTION\n")

print("Predicted House Price:",
      round(predicted_price[0], 2))

plt.figure(figsize=(8,6))

plt.scatter(y, y_pred, color='blue')

plt.plot([y.min(), y.max()],
         [y.min(), y.max()],
         color='red')

plt.xlabel("Actual Prices")
plt.ylabel("Predicted Prices")

plt.title("Actual vs Predicted Prices")

plt.grid(True)

plt.show()

