# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V1V7NyK8AxhoyFGgW_rvIoebL4V0vEC5
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df=pd.read_csv("/content/housing.csv")

print(df)

print(df.shape)

print(df.head(10))

print(df.tail(10))

print (df.columns)

print(df['total_rooms'])

x=df['total_rooms'].head(150).values.reshape(-1,1)
y=df['median_house_value'].head(150).values.reshape(-1,1)

plt.scatter(x,y)
plt.xlabel('total_rooms')
plt.ylabel('median_house_value')
plt.title('Scatter Plot of total_rooms vs. median_house_value')
plt.show()

